### ISSUE TITLE
Time for release?

### ISSUE THREAD

**Issue by spigell** [AnotherGitProfile/eos_exporter#1]
Hi. Your exporter is really cool. Thank you. Could you please make a release with prebuild binary for x64 arch(linux)? It may be pretty useful for deploy this exporter with scm like chef or ansible.

**Comment by AnotherGitProfile** [comment]
@spigell Thank you for submitting an issue! I released the prebuild binaries of application in current state for you https://github.com/AnotherGitProfile/eos_exporter/releases/tag/v0.1.0. Thank you for your interest in the project!
